### ISSUE TITLE
为什么抓的包ip地址不对呢

### ISSUE THREAD

**Issue by qeq66** [x-nas/WinsockPacketEditor#31]
<img width="880" alt="image" src="https://github.com/user-attachments/assets/9fd684a0-7e90-4983-8c01-2fe2de7fe33e">

**Comment by x-nas** [comment]
这个地址的封包属于内部广播的，所有的封包都是0.0.0.0这个地址吗？

**Comment by qeq66** [comment]
> 这个地址的封包属于内部广播的，所有的封包都是0.0.0.0这个地址吗？

是的，用Wireshark抓包能看到实际地址。这个程序是Java的，好像跑在jvm里面

**Comment by x-nas** [comment]
哦，jvm相当于多了一层代理，我这个程序是抓应用层的数据的，wireshark是抓物理层的所以能抓到ip地址，解决办法可以试试看自己再加一个代理，比如ccprox，然后注入这个代理来抓包

**Comment by qeq66** [comment]
https://www.x-nas.com/wpe/publish.htm 域名好像被墙了。打不开软件了

**Comment by x-nas** [comment]
> https://www.x-nas.com/wpe/publish.htm 域名好像被墙了。打不开软件了

我挂的cloudflare速度有点慢，多刷新几次试试看
