### ISSUE TITLE
Filter IP Only Display not working

### ISSUE THREAD

**Issue by kid95nd** [x-nas/WinsockPacketEditor#46]
In the packet list there is ip 103.190.202.36 but when using ip filter it doesn't show up, can you check for me?
![image](https://github.com/user-attachments/assets/f125c7dd-74a3-4be7-9acc-b27f22fe3e68)
![image](https://github.com/user-attachments/assets/316a800f-80cd-4c76-a0c8-6b07b83ff362)

**Comment by x-nas** [comment]
This is a bug that will be fixed in the next version. 

Thanks for your feedback！

**Comment by kid95nd** [comment]
Thank you for your response, I am really looking forward to the upcoming update.
