### ISSUE TITLE
注入不显示窗口

### ISSUE THREAD

**Issue by PersonForever** [x-nas/WinsockPacketEditor#49]
作者您好 本人小白一枚刚接触这些 本地搭建一个游戏服务端 服务端由多个win服务应用程序组成 想分析服务端客户端交互的数据 注入客户端正常出现窗口 但当我想分析服务端之间的数据时发现注入后不会显示窗口 但是注入是成功的 我使用PCHunter工具查看内存的确注入没问题 可能是因为注入的服务端没有窗口不是控制台程序并且是windows服务应用程序 没办法直接打开只能通过新建windows服务运行 我知道有个代理的方法 但是我目前能力有限 国内也没办法找到相应的教程 所以抛弃代理这条路想看看作者有没有办法解决

**Comment by x-nas** [comment]
注入没有窗口是因为注入的是一个没有窗体的 windows service 服务，所以WPE64的窗口也就没办法弹出了，解决办法通常都是用代理来转发，代理软件很多的，比较有名的是 CCProxy 和 Charles B站也有很多教程，从搭建环境到实战都有，建议可以从这里入手。

**Comment by PersonForever** [comment]
> 注入没有窗口是因为注入的是一个没有窗体的 windows service 服务，所以WPE64的窗口也就没办法弹出了，解决办法通常都是用代理来转发，代理软件很多的，比较有名的是 CCProxy 和 Charles B站也有很多教程，从搭建环境到实战都有，建议可以从这里入手。

感谢
